-- CVOptimizador Storage Bucket Configuration
-- Run this migration to create the cv-pdfs bucket for PDF storage

-- Create the storage bucket for CV PDFs
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'cv-pdfs',
  'cv-pdfs',
  false,  -- Private bucket, access via signed URLs only
  5242880,  -- 5MB max file size
  ARRAY['application/pdf']
);

-- Storage policies: only service role can upload/delete
-- Users can only read via signed URLs (handled by service role)

-- Allow service role to upload PDFs
CREATE POLICY "Service role can upload PDFs"
ON storage.objects FOR INSERT
TO service_role
WITH CHECK (bucket_id = 'cv-pdfs');

-- Allow service role to read PDFs (for signed URL generation)
CREATE POLICY "Service role can read PDFs"
ON storage.objects FOR SELECT
TO service_role
USING (bucket_id = 'cv-pdfs');

-- Allow service role to delete PDFs (for cleanup)
CREATE POLICY "Service role can delete PDFs"
ON storage.objects FOR DELETE
TO service_role
USING (bucket_id = 'cv-pdfs');

-- Note: End users download via signed URLs generated by service role
-- No direct user access to storage objects needed
